spring.application.name=demo-project
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo_project}
spring.datasource.username=${DB_USERNAME:demo}
spring.datasource.password=${DB_PASSWORD:demo}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
