spring.application.name=demo-project

auth.jwt.secret=${AUTH_JWT_SECRET}
auth.jwt.access-token-ttl=15m
auth.jwt.refresh-token-ttl=7d
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
